# Generated by Django 3.1.5 on 2021-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useri',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
    ]
