# Generated by Django 3.1.5 on 2021-06-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210610_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users_in_room',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='UserI',
        ),
    ]
