# Generated by Django 3.1.5 on 2021-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210610_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
